/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '@angular/http/src/http_module';
import * as import9 from '@angular/common/src/localization';
import * as import10 from '@angular/core/src/application_init';
import * as import11 from '@angular/core/src/testability/testability';
import * as import12 from '@angular/core/src/application_ref';
import * as import13 from '@angular/core/src/linker/compiler';
import * as import14 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import15 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import16 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import17 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import18 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import19 from '@angular/core/src/linker/view_utils';
import * as import20 from '@angular/platform-browser/src/browser/title';
import * as import21 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import22 from '@angular/forms/src/form_builder';
import * as import23 from '@angular/http/src/backends/browser_xhr';
import * as import24 from '@angular/http/src/base_response_options';
import * as import25 from '@angular/http/src/backends/xhr_backend';
import * as import26 from '@angular/http/src/base_request_options';
import * as import27 from '@angular/core/src/di/injector';
import * as import28 from './app.component.ngfactory';
import * as import29 from '@angular/core/src/application_tokens';
import * as import30 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import31 from '@angular/platform-browser/src/dom/events/key_events';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import34 from '@angular/core/src/console';
import * as import35 from '@angular/core/src/i18n/tokens';
import * as import36 from '@angular/core/src/error_handler';
import * as import37 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import38 from '@angular/platform-browser/src/dom/animation_driver';
import * as import39 from '@angular/core/src/render/api';
import * as import40 from '@angular/core/src/security';
import * as import41 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import42 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import43 from '@angular/http/src/interfaces';
import * as import44 from '@angular/http/src/http';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ReactiveFormsModule_5:import6.ReactiveFormsModule;
  _RouterModule_6:import7.RouterModule;
  _HttpModule_7:import8.HttpModule;
  _AppModule_8:import1.AppModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import9.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ApplicationInitStatus_12:import10.ApplicationInitStatus;
  _Testability_13:import11.Testability;
  _ApplicationRef__14:import12.ApplicationRef_;
  __ApplicationRef_15:any;
  __Compiler_16:import13.Compiler;
  __APP_ID_17:any;
  __DOCUMENT_18:any;
  __HAMMER_GESTURE_CONFIG_19:import14.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_20:any[];
  __EventManager_21:import15.EventManager;
  __DomSharedStylesHost_22:import16.DomSharedStylesHost;
  __AnimationDriver_23:any;
  __DomRootRenderer_24:import17.DomRootRenderer_;
  __RootRenderer_25:any;
  __DomSanitizer_26:import18.DomSanitizerImpl;
  __Sanitizer_27:any;
  __ViewUtils_28:import19.ViewUtils;
  __IterableDiffers_29:any;
  __KeyValueDiffers_30:any;
  __SharedStylesHost_31:any;
  __Title_32:import20.Title;
  __RadioControlRegistry_33:import21.RadioControlRegistry;
  __FormBuilder_34:import22.FormBuilder;
  __BrowserXhr_35:import23.BrowserXhr;
  __ResponseOptions_36:import24.BaseResponseOptions;
  __XSRFStrategy_37:any;
  __XHRBackend_38:import25.XHRBackend;
  __RequestOptions_39:import26.BaseRequestOptions;
  __Http_40:any;
  constructor(parent:import27.Injector) {
    super(parent,[import28.AppComponentNgFactory],[import28.AppComponentNgFactory]);
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == null)) { (this.__LOCALE_ID_9 = 'en-US'); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == null)) { (this.__NgLocalization_10 = new import9.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_15():any {
    if ((this.__ApplicationRef_15 == null)) { (this.__ApplicationRef_15 = this._ApplicationRef__14); }
    return this.__ApplicationRef_15;
  }
  get _Compiler_16():import13.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import13.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import29._appIdRandomProviderFactory()); }
    return this.__APP_ID_17;
  }
  get _DOCUMENT_18():any {
    if ((this.__DOCUMENT_18 == null)) { (this.__DOCUMENT_18 = import4._document()); }
    return this.__DOCUMENT_18;
  }
  get _HAMMER_GESTURE_CONFIG_19():import14.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_19 == null)) { (this.__HAMMER_GESTURE_CONFIG_19 = new import14.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_19;
  }
  get _EVENT_MANAGER_PLUGINS_20():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_20 == null)) { (this.__EVENT_MANAGER_PLUGINS_20 = [
      new import30.DomEventsPlugin(),
      new import31.KeyEventsPlugin(),
      new import14.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_19)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_20;
  }
  get _EventManager_21():import15.EventManager {
    if ((this.__EventManager_21 == null)) { (this.__EventManager_21 = new import15.EventManager(this._EVENT_MANAGER_PLUGINS_20,this.parent.get(import32.NgZone))); }
    return this.__EventManager_21;
  }
  get _DomSharedStylesHost_22():import16.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_22 == null)) { (this.__DomSharedStylesHost_22 = new import16.DomSharedStylesHost(this._DOCUMENT_18)); }
    return this.__DomSharedStylesHost_22;
  }
  get _AnimationDriver_23():any {
    if ((this.__AnimationDriver_23 == null)) { (this.__AnimationDriver_23 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_23;
  }
  get _DomRootRenderer_24():import17.DomRootRenderer_ {
    if ((this.__DomRootRenderer_24 == null)) { (this.__DomRootRenderer_24 = new import17.DomRootRenderer_(this._DOCUMENT_18,this._EventManager_21,this._DomSharedStylesHost_22,this._AnimationDriver_23,this._APP_ID_17)); }
    return this.__DomRootRenderer_24;
  }
  get _RootRenderer_25():any {
    if ((this.__RootRenderer_25 == null)) { (this.__RootRenderer_25 = import33._createConditionalRootRenderer(this._DomRootRenderer_24,this.parent.get(import33.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_25;
  }
  get _DomSanitizer_26():import18.DomSanitizerImpl {
    if ((this.__DomSanitizer_26 == null)) { (this.__DomSanitizer_26 = new import18.DomSanitizerImpl()); }
    return this.__DomSanitizer_26;
  }
  get _Sanitizer_27():any {
    if ((this.__Sanitizer_27 == null)) { (this.__Sanitizer_27 = this._DomSanitizer_26); }
    return this.__Sanitizer_27;
  }
  get _ViewUtils_28():import19.ViewUtils {
    if ((this.__ViewUtils_28 == null)) { (this.__ViewUtils_28 = new import19.ViewUtils(this._RootRenderer_25,this._Sanitizer_27)); }
    return this.__ViewUtils_28;
  }
  get _IterableDiffers_29():any {
    if ((this.__IterableDiffers_29 == null)) { (this.__IterableDiffers_29 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_29;
  }
  get _KeyValueDiffers_30():any {
    if ((this.__KeyValueDiffers_30 == null)) { (this.__KeyValueDiffers_30 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_30;
  }
  get _SharedStylesHost_31():any {
    if ((this.__SharedStylesHost_31 == null)) { (this.__SharedStylesHost_31 = this._DomSharedStylesHost_22); }
    return this.__SharedStylesHost_31;
  }
  get _Title_32():import20.Title {
    if ((this.__Title_32 == null)) { (this.__Title_32 = new import20.Title()); }
    return this.__Title_32;
  }
  get _RadioControlRegistry_33():import21.RadioControlRegistry {
    if ((this.__RadioControlRegistry_33 == null)) { (this.__RadioControlRegistry_33 = new import21.RadioControlRegistry()); }
    return this.__RadioControlRegistry_33;
  }
  get _FormBuilder_34():import22.FormBuilder {
    if ((this.__FormBuilder_34 == null)) { (this.__FormBuilder_34 = new import22.FormBuilder()); }
    return this.__FormBuilder_34;
  }
  get _BrowserXhr_35():import23.BrowserXhr {
    if ((this.__BrowserXhr_35 == null)) { (this.__BrowserXhr_35 = new import23.BrowserXhr()); }
    return this.__BrowserXhr_35;
  }
  get _ResponseOptions_36():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_36 == null)) { (this.__ResponseOptions_36 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_36;
  }
  get _XSRFStrategy_37():any {
    if ((this.__XSRFStrategy_37 == null)) { (this.__XSRFStrategy_37 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_37;
  }
  get _XHRBackend_38():import25.XHRBackend {
    if ((this.__XHRBackend_38 == null)) { (this.__XHRBackend_38 = new import25.XHRBackend(this._BrowserXhr_35,this._ResponseOptions_36,this._XSRFStrategy_37)); }
    return this.__XHRBackend_38;
  }
  get _RequestOptions_39():import26.BaseRequestOptions {
    if ((this.__RequestOptions_39 == null)) { (this.__RequestOptions_39 = new import26.BaseRequestOptions()); }
    return this.__RequestOptions_39;
  }
  get _Http_40():any {
    if ((this.__Http_40 == null)) { (this.__Http_40 = import8.httpFactory(this._XHRBackend_38,this._RequestOptions_39)); }
    return this.__Http_40;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ReactiveFormsModule_5 = new import6.ReactiveFormsModule();
    this._RouterModule_6 = new import7.RouterModule(this.parent.get(import7.ROUTER_FORROOT_GUARD,(null as any)));
    this._HttpModule_7 = new import8.HttpModule();
    this._AppModule_8 = new import1.AppModule();
    this._ErrorHandler_11 = import4.errorHandler();
    this._ApplicationInitStatus_12 = new import10.ApplicationInitStatus(this.parent.get(import10.APP_INITIALIZER,(null as any)));
    this._Testability_13 = new import11.Testability(this.parent.get(import32.NgZone));
    this._ApplicationRef__14 = new import12.ApplicationRef_(this.parent.get(import32.NgZone),this.parent.get(import34.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_12,this.parent.get(import11.TestabilityRegistry,(null as any)),this._Testability_13);
    return this._AppModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import8.HttpModule)) { return this._HttpModule_7; }
    if ((token === import1.AppModule)) { return this._AppModule_8; }
    if ((token === import35.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import36.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import10.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import11.Testability)) { return this._Testability_13; }
    if ((token === import12.ApplicationRef_)) { return this._ApplicationRef__14; }
    if ((token === import12.ApplicationRef)) { return this._ApplicationRef_15; }
    if ((token === import13.Compiler)) { return this._Compiler_16; }
    if ((token === import29.APP_ID)) { return this._APP_ID_17; }
    if ((token === import37.DOCUMENT)) { return this._DOCUMENT_18; }
    if ((token === import14.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_19; }
    if ((token === import15.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_20; }
    if ((token === import15.EventManager)) { return this._EventManager_21; }
    if ((token === import16.DomSharedStylesHost)) { return this._DomSharedStylesHost_22; }
    if ((token === import38.AnimationDriver)) { return this._AnimationDriver_23; }
    if ((token === import17.DomRootRenderer)) { return this._DomRootRenderer_24; }
    if ((token === import39.RootRenderer)) { return this._RootRenderer_25; }
    if ((token === import18.DomSanitizer)) { return this._DomSanitizer_26; }
    if ((token === import40.Sanitizer)) { return this._Sanitizer_27; }
    if ((token === import19.ViewUtils)) { return this._ViewUtils_28; }
    if ((token === import41.IterableDiffers)) { return this._IterableDiffers_29; }
    if ((token === import42.KeyValueDiffers)) { return this._KeyValueDiffers_30; }
    if ((token === import16.SharedStylesHost)) { return this._SharedStylesHost_31; }
    if ((token === import20.Title)) { return this._Title_32; }
    if ((token === import21.RadioControlRegistry)) { return this._RadioControlRegistry_33; }
    if ((token === import22.FormBuilder)) { return this._FormBuilder_34; }
    if ((token === import23.BrowserXhr)) { return this._BrowserXhr_35; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_36; }
    if ((token === import43.XSRFStrategy)) { return this._XSRFStrategy_37; }
    if ((token === import25.XHRBackend)) { return this._XHRBackend_38; }
    if ((token === import26.RequestOptions)) { return this._RequestOptions_39; }
    if ((token === import44.Http)) { return this._Http_40; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__14.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);