/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['div[_ngcontent-%COMP%] {\n  width:100px;\n  height:100px;\n  > a {\n    color:red;\n  }\n  >span {\n    color:blue\n  }\n}'];