/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/13-组件通信/brother1son1';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/13-组件通信/brother.service';
import * as import9 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import10 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import11 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '@angular/core/src/linker/element_ref';
import * as import13 from '@angular/forms/src/directives/default_value_accessor';
import * as import14 from '@angular/forms/src/directives/control_value_accessor';
import * as import15 from '@angular/forms/src/directives/ng_model';
import * as import16 from '@angular/forms/src/directives/ng_control';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_Brother1Son1Component {
  /*private*/ _eventHandler:Function;
  context:import0.Brother1Son1Component;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.Brother1Son1Component(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_Brother1Son1Component_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_Brother1Son1Component_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.Brother1Son1Component>;
  _Brother1Son1Component_0_3:Wrapper_Brother1Son1Component;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Brother1Son1Component_Host0,renderType_Brother1Son1Component_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'brother1son1',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_Brother1Son1Component0(this.viewUtils,this,0,this._el_0);
    this._Brother1Son1Component_0_3 = new Wrapper_Brother1Son1Component(this.injectorGet(import8.BrotherService,this.parentIndex));
    this.compView_0.create(this._Brother1Son1Component_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._Brother1Son1Component_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Brother1Son1Component) && (0 === requestNodeIndex))) { return this._Brother1Son1Component_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Brother1Son1Component_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const Brother1Son1ComponentNgFactory:import7.ComponentFactory<import0.Brother1Son1Component> = new import7.ComponentFactory<import0.Brother1Son1Component>('brother1son1',View_Brother1Son1Component_Host0,import0.Brother1Son1Component);
const styles_Brother1Son1Component:any[] = ([] as any[]);
var renderType_Brother1Son1Component:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_Brother1Son1Component,{});
export class View_Brother1Son1Component0 extends import1.AppView<import0.Brother1Son1Component> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _DefaultValueAccessor_3_3:import9.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_3_4:any[];
  _NgModel_3_5:import10.Wrapper_NgModel;
  _NgControl_3_6:any;
  _NgControlStatus_3_7:import11.Wrapper_NgControlStatus;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _DefaultValueAccessor_8_3:import9.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_8_4:any[];
  _NgModel_8_5:import10.Wrapper_NgModel;
  _NgControl_8_6:any;
  _NgControlStatus_8_7:import11.Wrapper_NgControlStatus;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Brother1Son1Component0,renderType_Brother1Son1Component,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_21 = import6.UNINITIALIZED;
    this._expr_22 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    brother1son1:\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'input',new import3.InlineArray2(2,'placeholder','name'),(null as any));
    this._DefaultValueAccessor_3_3 = new import9.Wrapper_DefaultValueAccessor(this.renderer,new import12.ElementRef(this._el_3));
    this._NG_VALUE_ACCESSOR_3_4 = [this._DefaultValueAccessor_3_3.context];
    this._NgModel_3_5 = new import10.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_3_4);
    this._NgControl_3_6 = this._NgModel_3_5.context;
    this._NgControlStatus_3_7 = new import11.Wrapper_NgControlStatus(this._NgControl_3_6);
    this._text_4 = this.renderer.createText(this._el_1,'',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    brother1son1 user.name:\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'input',new import3.InlineArray2(2,'placeholder','name'),(null as any));
    this._DefaultValueAccessor_8_3 = new import9.Wrapper_DefaultValueAccessor(this.renderer,new import12.ElementRef(this._el_8));
    this._NG_VALUE_ACCESSOR_8_4 = [this._DefaultValueAccessor_8_3.context];
    this._NgModel_8_5 = new import10.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_8_4);
    this._NgControl_8_6 = this._NgModel_8_5.context;
    this._NgControlStatus_8_7 = new import11.Wrapper_NgControlStatus(this._NgControl_8_6);
    this._text_9 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_3,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_3));
    this._NgModel_3_5.subscribe(this,this.eventHandler(this.handleEvent_3),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_8));
    this._NgModel_8_5.subscribe(this,this.eventHandler(this.handleEvent_8),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.DefaultValueAccessor) && (3 === requestNodeIndex))) { return this._DefaultValueAccessor_3_3.context; }
    if (((token === import14.NG_VALUE_ACCESSOR) && (3 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_3_4; }
    if (((token === import15.NgModel) && (3 === requestNodeIndex))) { return this._NgModel_3_5.context; }
    if (((token === import16.NgControl) && (3 === requestNodeIndex))) { return this._NgControl_3_6; }
    if (((token === import17.NgControlStatus) && (3 === requestNodeIndex))) { return this._NgControlStatus_3_7.context; }
    if (((token === import13.DefaultValueAccessor) && (8 === requestNodeIndex))) { return this._DefaultValueAccessor_8_3.context; }
    if (((token === import14.NG_VALUE_ACCESSOR) && (8 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_8_4; }
    if (((token === import15.NgModel) && (8 === requestNodeIndex))) { return this._NgModel_8_5.context; }
    if (((token === import16.NgControl) && (8 === requestNodeIndex))) { return this._NgControl_8_6; }
    if (((token === import17.NgControlStatus) && (8 === requestNodeIndex))) { return this._NgControlStatus_8_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_3_1_0:any = this.context.name;
    this._NgModel_3_5.check_model(currVal_3_1_0,throwOnChange,false);
    this._NgModel_3_5.ngDoCheck(this,this._el_3,throwOnChange);
    this._NgControlStatus_3_7.ngDoCheck(this,this._el_3,throwOnChange);
    this._DefaultValueAccessor_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_8_1_0:any = this.context.user.name;
    this._NgModel_8_5.check_model(currVal_8_1_0,throwOnChange,false);
    this._NgModel_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    this._NgControlStatus_8_7.ngDoCheck(this,this._el_8,throwOnChange);
    this._NgControlStatus_3_7.checkHost(this,this,this._el_3,throwOnChange);
    const currVal_21:any = import3.inlineInterpolate(1,'\n    ',this.context.name,'\n');
    if (import3.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_4,currVal_21);
      this._expr_21 = currVal_21;
    }
    this._NgControlStatus_8_7.checkHost(this,this,this._el_8,throwOnChange);
    const currVal_22:any = import3.inlineInterpolate(1,'\n    ',this.context.user.name,'\n');
    if (import3.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setText(this._text_9,currVal_22);
      this._expr_22 = currVal_22;
    }
  }
  destroyInternal():void {
    this._NgModel_3_5.ngOnDestroy();
    this._NgModel_8_5.ngOnDestroy();
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_3_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_8_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.user.name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}